# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-12 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=1000)),
                ('commitsFile', models.CharField(max_length=2000)),
                ('nvalue', models.CharField(max_length=2000)),
                ('commit_date', models.DateTimeField(default='2015-01-01 10:37:54')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Webents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastPubDate', models.DateTimeField(verbose_name='date published')),
                ('add_date', models.DateTimeField(verbose_name='date published')),
                ('lastPubStatus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gitlog.Profiles')),
            ],
        ),
    ]
